
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 47
#define YY_END_OF_BUFFER 48
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[174] =
    {   0,
       20,   20,   48,   46,    1,    2,    1,   30,   25,   46,
       46,   31,   32,   24,   37,   24,   46,   25,   19,   38,
       27,   28,   27,   23,   23,   35,   36,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   33,   46,   34,
        1,    2,   27,   29,   44,    0,   43,   44,   26,   39,
       20,   45,    0,   19,   41,   41,   23,   23,    0,   40,
       20,   23,   23,   23,   23,   23,    7,   23,   23,   23,
        3,   23,   23,   23,   23,   23,    0,   21,    0,    0,
       39,    0,   39,   20,   41,   45,    0,   41,   41,   20,
       20,   40,   40,   20,   23,   23,   23,   23,   23,   23,

       23,   23,   23,    5,    9,   23,   23,   23,   23,   42,
       44,   22,   22,    0,   39,   39,    0,   20,   20,   41,
       20,   41,   40,    0,   23,   23,   16,   10,   23,   23,
       23,    4,   23,   23,   23,   13,   23,   39,   41,   20,
        0,   20,   41,   40,    0,   23,    8,   23,   23,   23,
       11,   23,   23,    6,    0,   39,   20,    0,   41,    0,
       23,   23,   12,   14,   15,   39,   39,    0,   23,   17,
       39,   18,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    1,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,    1,   19,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   24,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       25,   26,   27,    1,   23,    1,   28,   29,   30,   31,

       32,   33,   23,   34,   35,   23,   36,   37,   23,   38,
       39,   23,   23,   40,   41,   42,   43,   44,   45,   23,
       23,   23,   46,   47,   48,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[49] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    4,    1,    5,    5,    1,    1,
        1,    1,    5,    5,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    1
    } ;

static const flex_int16_t yy_base[181] =
    {   0,
        0,    0,  191,  525,   47,  525,   50,  168,  525,  169,
       51,  525,  525,  160,  525,  154,   43,  151,   47,  525,
      123,  114,  109,   39,   55,  525,  525,   57,   64,   67,
       90,   70,   72,   76,   78,   83,   94,  525,   74,  525,
       64,  525,  525,  525,  108,   96,   94,  121,  525,  100,
      116,   80,  124,  128,   96,  152,  102,  108,  138,  156,
      160,  119,  140,  162,  165,  168,  170,  176,  179,  181,
      187,  189,  191,  193,  197,  202,   78,  525,   75,   72,
      212,  228,  232,    0,  240,   67,   60,  205,  207,  244,
      248,  252,  256,    0,  265,  267,  221,  269,  271,  273,

      275,  279,  282,  217,  285,  288,  290,  297,  299,  525,
      525,  525,  525,  301,  303,  305,  307,  323,    0,  330,
        0,  337,  309,  316,  328,  335,  339,  341,  343,  345,
      347,  349,  351,  355,  357,  359,  362,  365,  384,  388,
      368,  392,  396,  373,  400,  404,  382,  406,  408,  410,
      412,  414,  416,  418,  420,  431,  436,  440,  444,  448,
      450,  422,  452,  454,  456,  460,  464,  468,  470,  472,
      477,  479,  525,  502,  504,   58,  509,  514,   45,  519
    } ;

static const flex_int16_t yy_def[181] =
    {   0,
      173,    1,  173,  173,  173,  173,  173,  173,  173,  173,
      174,  173,  173,  173,  173,  173,  173,  173,  175,  173,
      173,  173,  173,  176,  176,  173,  173,  176,  176,  176,
       25,  176,  176,  176,  176,  176,  176,  173,  173,  173,
      173,  173,  173,  173,  177,  177,  177,  177,  173,  173,
      175,  178,  173,  175,  179,  179,  176,  176,  173,  173,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  177,  173,  180,  177,
      173,  173,  173,   51,  179,  178,  178,  179,  179,  179,
       51,  173,  173,   61,  176,  176,  176,  176,  176,  176,

      176,  176,  176,  176,  176,  176,  176,  176,  176,  173,
      173,  173,  173,  173,  173,   51,  173,   90,   90,  179,
       91,  179,   91,  173,   61,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,   51,  179,   91,
      173,   90,   90,   91,   91,   61,  176,  176,  176,  176,
      176,  176,  176,  176,  173,   90,   91,   91,   90,   91,
      176,  176,  176,  176,  176,   91,   90,   91,  176,  176,
       91,  176,    0,  173,  173,  173,  173,  173,  173,  173
    } ;

static const flex_int16_t yy_nxt[574] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
        9,   14,   15,   16,   17,   18,   19,   19,   20,   21,
       22,   23,   24,   25,   26,    4,   27,   24,   28,   29,
       30,   31,   32,   24,   33,   24,   24,   24,   24,   34,
       35,   24,   24,   36,   37,   38,   39,   40,   41,   89,
       41,   41,   42,   41,   46,   57,   57,   50,   47,   51,
       51,   53,   58,   54,   54,   41,   59,   41,   59,   60,
       56,   61,   61,   57,   57,  173,   48,   87,   56,  113,
       57,   57,  112,   57,   57,  110,   57,   57,   57,   57,
       87,   63,   57,   57,   57,   57,   62,   64,   66,   57,

       57,   78,   65,  173,   71,   67,   69,   73,   70,   72,
       57,   57,   88,   88,   50,   78,   81,   81,   57,   57,
       44,   75,   74,   82,   57,   57,   68,   76,   79,   43,
       83,   82,   84,   84,   43,   57,   57,   80,   50,   85,
       51,   51,   53,   43,   54,   54,   80,   85,   80,   80,
       96,   56,   60,   80,   91,   91,   57,   57,   80,   56,
       80,   52,   80,   59,   80,   59,   60,   49,   90,   90,
       60,   49,   92,   92,   93,   44,   94,   94,   57,   57,
       97,   57,   57,   95,   57,   57,   57,   57,   43,   98,
      173,   95,   57,   57,  173,   57,   57,   57,   57,  173,

      100,  173,   99,   57,   57,   57,   57,   57,   57,   57,
       57,  173,  101,   57,   57,  173,  102,  103,   57,   57,
      104,   88,   88,   88,   88,  173,   50,  107,   81,   81,
      105,  108,  106,   57,   57,   82,  109,   57,   57,  114,
      173,  114,  173,   82,  115,  115,   50,  173,  116,  116,
      173,  117,  127,  117,  173,   82,  118,  118,   93,  173,
      119,  119,   93,   82,  121,  121,   60,  120,   92,   92,
       60,  122,  123,  123,  173,  120,  124,  173,  124,  122,
      173,  125,  125,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,  173,  126,   57,   57,  173,   57,   57,

      130,   57,   57,  131,   57,   57,   57,   57,  128,  133,
      132,  173,  129,   57,   57,   57,   57,  115,  115,  115,
      115,  138,  138,  140,  140,  144,  144,  136,  139,  173,
      134,  135,  145,  145,  173,  137,  139,  141,  173,  142,
      142,  124,  141,  124,  146,  146,  143,  143,  124,  173,
      124,   57,   57,  143,  143,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,  173,
      147,   57,   57,   57,   57,   57,   57,  148,   57,   57,
      173,  138,  138,  150,  158,  158,  153,  149,  139,  144,
      144,  173,  151,  154,  152,  155,  139,  155,   57,   57,

      156,  156,  141,  173,  157,  157,  141,  173,  142,  142,
      141,  173,  159,  159,  141,  173,  160,  160,  141,  173,
      146,  146,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,  166,  166,   57,   57,
      173,  163,  173,  161,  162,  141,  173,  167,  167,  165,
      141,  164,  157,  157,  141,  173,  168,  168,  141,  173,
      159,  159,  141,  170,  160,  160,   57,   57,   57,   57,
       57,   57,   57,   57,  141,  173,  171,  171,  141,  173,
      167,  167,  141,  173,  168,  168,   57,   57,   57,   57,
      173,  141,  169,  171,  171,   57,   57,  173,  173,  173,

      173,  172,   45,  173,   45,   45,   45,   55,   55,   77,
      173,  173,   77,   77,   86,   86,   86,   86,   86,  111,
      173,  173,  111,  111,    3,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173
    } ;

static const flex_int16_t yy_chk[574] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,  179,
        5,    7,    7,    7,   11,   24,   24,   17,   11,   17,
       17,   19,  176,   19,   19,   41,   25,   41,   25,   25,
       19,   25,   25,   28,   28,   87,   11,   86,   19,   80,
       29,   29,   79,   30,   30,   77,   32,   32,   33,   33,
       52,   29,   34,   34,   35,   35,   28,   29,   30,   36,

       36,   47,   29,   46,   33,   30,   32,   34,   32,   33,
       37,   37,   55,   55,   50,   45,   50,   50,   57,   57,
       39,   36,   35,   50,   58,   58,   31,   37,   48,   23,
       51,   50,   51,   51,   22,   62,   62,   48,   53,   51,
       53,   53,   54,   21,   54,   54,   48,   51,   48,   48,
       62,   54,   59,   48,   59,   59,   63,   63,   48,   54,
       48,   18,   48,   56,   48,   56,   56,   16,   56,   56,
       60,   14,   60,   60,   61,   10,   61,   61,   64,   64,
       63,   65,   65,   61,   66,   66,   67,   67,    8,   64,
        3,   61,   68,   68,    0,   69,   69,   70,   70,    0,

       66,    0,   65,   71,   71,   72,   72,   73,   73,   74,
       74,    0,   67,   75,   75,    0,   68,   69,   76,   76,
       70,   88,   88,   89,   89,    0,   81,   74,   81,   81,
       72,   75,   73,  104,  104,   81,   76,   97,   97,   82,
        0,   82,    0,   81,   82,   82,   83,    0,   83,   83,
        0,   85,   97,   85,    0,   83,   85,   85,   90,    0,
       90,   90,   91,   83,   91,   91,   92,   90,   92,   92,
       93,   91,   93,   93,    0,   90,   95,    0,   95,   91,
        0,   95,   95,   96,   96,   98,   98,   99,   99,  100,
      100,  101,  101,    0,   96,  102,  102,    0,  103,  103,

      100,  105,  105,  101,  106,  106,  107,  107,   98,  103,
      102,    0,   99,  108,  108,  109,  109,  114,  114,  115,
      115,  116,  116,  117,  117,  123,  123,  108,  116,    0,
      106,  107,  124,  124,    0,  109,  116,  118,    0,  118,
      118,  120,  125,  120,  125,  125,  120,  120,  122,    0,
      122,  126,  126,  122,  122,  127,  127,  128,  128,  129,
      129,  130,  130,  131,  131,  132,  132,  133,  133,    0,
      126,  134,  134,  135,  135,  136,  136,  129,  137,  137,
        0,  138,  138,  131,  141,  141,  135,  130,  138,  144,
      144,    0,  133,  137,  134,  139,  138,  139,  147,  147,

      139,  139,  140,    0,  140,  140,  142,    0,  142,  142,
      143,    0,  143,  143,  145,    0,  145,  145,  146,    0,
      146,  146,  148,  148,  149,  149,  150,  150,  151,  151,
      152,  152,  153,  153,  154,  154,  155,  155,  162,  162,
        0,  150,    0,  148,  149,  156,    0,  156,  156,  153,
      157,  152,  157,  157,  158,    0,  158,  158,  159,    0,
      159,  159,  160,  162,  160,  160,  161,  161,  163,  163,
      164,  164,  165,  165,  166,    0,  166,  166,  167,    0,
      167,  167,  168,    0,  168,  168,  169,  169,  170,  170,
        0,  171,  161,  171,  171,  172,  172,    0,    0,    0,

        0,  169,  174,    0,  174,  174,  174,  175,  175,  177,
        0,    0,  177,  177,  178,  178,  178,  178,  178,  180,
        0,    0,  180,  180,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[48] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Lexical.l"
/*%x STRING*/
/*%x SINGLE_LINE_COMMENT*/
/*%x MULTI_LINE_COMMENT*/
#line 8 "Lexical.l"
  #include <bits/stdc++.h>
  #include "symbolTable.h"
  #include "y.tab.h"
  using namespace std;

  //ofstream tokenout;

  //symbolTable st(10);
  //bool isMultiLineString=false;

  string getEscapeChar(char ch){
	if(ch=='n')
		return "\n";
	else if(ch=='t')
		return "\t";
	else if(ch=='\\')
		return "\\";
	else if(ch=='\'')
		return "\'";
	else if(ch=='a')
		return "\a";
	else if(ch=='f')
		return "\f";
	else if(ch=='r')
	return "\r";
	else if(ch=='b')
		return "\b";
	else if(ch=='v')
		return "\v";
	else if(ch=='0')
		return "\0";
	else if(ch=='\"')
		return "\"";
	else return "Nothing";
}

string str;
string str2;
int startLine;
int line_count=1;
int error_count=0;


void PrintLogFile(int line, string token,string lexeme, bool IsNewline=true){
  /*int l=lexeme.size();
  if(lexeme[l-1]=='\n')
    lexeme[l-1]='\0';*/

  cout<<"Line# "<<line<<": Token <" << token << "> Lexeme " << lexeme <<" found";
  if(IsNewline) cout<<endl;
}

void PrintLogFileError(int line,string error,string lexeme,bool IsNewline=true){
  /*Error at line# 1: TOO_MANY_DECIMAL_POINTS 1.2.345*/
  error_count++;
  cout<<"Error at line# "<<line<<": "<<error<<" "<<lexeme;
  if(IsNewline) cout<<endl;

}

void PrintTokenFile(string token, string lexeme){
  //tokenout<<"<" << token <<", "<<lexeme<<">"<<endl;
}
void PrintTokenFile(string token){
  //tokenout<< "<" <<token << "> "<<endl;
}


#line 724 "lex.yy.c"
/*pattern=======================*/
/*ERRORS=========================================================*/
#line 727 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 106 "Lexical.l"

#line 946 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 174 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 525 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 107 "Lexical.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 108 "Lexical.l"
{line_count++;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 110 "Lexical.l"
{
  string token="IF";
  string keyword="if";
  PrintLogFile(line_count, token, keyword);
  yylval.symbol=new symbolInfo(yytext,"IF",yylineno,yylineno);
  //PrintTokenFile(token,keyword);
  return IF;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 119 "Lexical.l"
{
  string token="ELSE";
  string keyword="else";
  PrintLogFile(line_count, token, keyword);
  yylval.symbol=new symbolInfo(yytext,"else",yylineno,yylineno);
  return ELSE;
  //PrintTokenFile(token,keyword);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 128 "Lexical.l"
{
  string token="FOR";
  string keyword="for";
  PrintLogFile(line_count, token, keyword);
  yylval.symbol=new symbolInfo(yytext,"FOR",yylineno,yylineno);
  return FOR;
  //PrintTokenFile(token,keyword);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 137 "Lexical.l"
{
  string token="WHILE";
  string keyword="while";
  PrintLogFile(line_count, token, keyword);
  yylval.symbol=new symbolInfo(yytext,"WHILE",yylineno,yylineno);
  return WHILE;
  //PrintTokenFile(token,keyword);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 146 "Lexical.l"
{
  string token="DO";
  string keyword="do";
  PrintLogFile(line_count, token, keyword);
  yylval.symbol=new symbolInfo(yytext,"DO",yylineno,yylineno);
  return DO;
  //PrintTokenFile(token,keyword);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 155 "Lexical.l"
{
  string token="BREAK";
  string keyword="break";
  PrintLogFile(line_count, token, keyword);
  yylval.symbol=new symbolInfo(yytext,"BREAK",yylineno,yylineno);
  return BREAK;
  //PrintTokenFile(token,keyword);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 164 "Lexical.l"
{
  string token="INT";
  string keyword="int";
  PrintLogFile(line_count, token, keyword);
  yylval.symbol=new symbolInfo(yytext,"INT",yylineno,yylineno);
  return INT;
  //PrintTokenFile(token,keyword);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 173 "Lexical.l"
{
  string token="CHAR";
  string keyword="char";
  PrintLogFile(line_count, token, keyword);
  yylval.symbol=new symbolInfo(yytext,"CHAR",yylineno,yylineno);
  return CHAR;
  //PrintTokenFile(token,keyword);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 182 "Lexical.l"
{
  string token="FLOAT";
  string keyword="float";
  PrintLogFile(line_count, token, keyword);
  yylval.symbol=new symbolInfo(yytext,"FLOAT",yylineno,yylineno);
  return FLOAT;
  //PrintTokenFile(token,keyword);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 191 "Lexical.l"
{
  string token="DOUBLE";
  string keyword="double";
  PrintLogFile(line_count, token, keyword);
  yylval.symbol=new symbolInfo(yytext,"DOUBLE",yylineno,yylineno);
  return DOUBLE;
  //PrintTokenFile(token,keyword);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 200 "Lexical.l"
{
  string token="VOID";
  string keyword="void";
  PrintLogFile(line_count, token, keyword);
  yylval.symbol=new symbolInfo(yytext,"VOID",yylineno,yylineno);
  return VOID;
  //PrintTokenFile(token,keyword);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 210 "Lexical.l"
{
  //-----------------------------printf goes here
  string token="RETURN";
  string keyword="return";
  PrintLogFile(line_count, token, keyword);
  //PrintTokenFile(token,keyword);
  yylval.symbol=new symbolInfo(yytext,"RETURN",yylineno,yylineno);
  return RETURN;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 220 "Lexical.l"
{
  string token="SWITCH";
  string keyword="switch";
  PrintLogFile(line_count, token, keyword);
  yylval.symbol=new symbolInfo(yytext,"SWITCH",yylineno,yylineno);
  return SWITCH;
  //PrintTokenFile(token,keyword);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 229 "Lexical.l"
{
  string token="CASE";
  string keyword="case";
  PrintLogFile(line_count, token, keyword);
  yylval.symbol=new symbolInfo(yytext,"CASE",yylineno,yylineno);
  return CASE;
  //PrintTokenFile(token,keyword);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 238 "Lexical.l"
{
  string token="DEFAULT";
  string keyword="default";
  PrintLogFile(line_count, token, keyword);
  yylval.symbol=new symbolInfo(yytext,"DEFAULT",yylineno,yylineno);
  return DEFAULT;
  //PrintTokenFile(token,keyword);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 246 "Lexical.l"
{
  string token="CONTINUE";
  string keyword="continue";
  PrintLogFile(line_count, token, keyword);
  yylval.symbol=new symbolInfo(yytext,"CONTINUE",yylineno,yylineno);
  return CONTINUE;
  //PrintTokenFile(token,keyword);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 255 "Lexical.l"
{
  string number = yytext;
  string token = "CONST_INT";
  PrintLogFile(line_count,token,number);
  //PrintTokenFile(token,number); 
  yylval.symbol=new symbolInfo(yytext,"CONST_INT",yylineno,yylineno);
  return CONST_INT;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 264 "Lexical.l"
{
  string number = yytext;
  string token = "CONST_FLOAT";
  PrintLogFile(line_count,token,number);
  yylval.symbol=new symbolInfo(yytext,"CONST_FLOAT",yylineno,yylineno);
  //PrintTokenFile(token,number); 
  return CONST_FLOAT;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 273 "Lexical.l"
{
  string character=yytext;
  string token="CONST_CHAR";

  
  string ch="";
  ch+=character[1];
  PrintLogFile(line_count, token, ch);
  /*cout<<" --> " << "<" <<token << ", "<<ch<<">" <<endl<<endl;*/
  //PrintTokenFile(token,ch);
  yylval.symbol=new symbolInfo(yytext,"CONST_CHAR",yylineno,yylineno);
  return CONST_CHAR;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 287 "Lexical.l"
{
  string character=yytext;
  string token="CONST_CHAR";

  string ch=getEscapeChar(character[2]);
  PrintLogFile(line_count,token,ch);
  //PrintTokenFile(token,ch);
  yylval.symbol=new symbolInfo(yytext,"CONST_CHAR",yylineno,yylineno);
  return CONST_CHAR;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 298 "Lexical.l"
{
  string id=yytext;
  string token="ID";
  PrintLogFile(line_count,token,id);
  //PrintTokenFile(token,id);
  //bool hasInserted = st.insert(id,token);
  //if(hasInserted) st.printAllScopeTable();
  yylval.symbol= new symbolInfo(yytext,"ID",yylineno,yylineno);
  return ID;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 309 "Lexical.l"
{
  string oprt=yytext;
  string token="ADDOP";
  PrintLogFile(line_count,token,oprt);
  //PrintTokenFile(token,oprt);
  yylval.symbol=new symbolInfo(yytext,"ADDOP",yylineno,yylineno);
  return ADDOP;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 317 "Lexical.l"
{
  string oprt=yytext;
  string token="MULOP";
  PrintLogFile(line_count,token,oprt);
  yylval.symbol=new symbolInfo(yytext,"MULOP",yylineno,yylineno);
  return MULOP;
  //PrintTokenFile(token,oprt);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 325 "Lexical.l"
{
  string oprt=yytext;
  string token="INCOP";
  PrintLogFile(line_count,token,oprt);
  //PrintTokenFile(token,oprt);
  yylval.symbol=new symbolInfo(yytext,"INCOP",yylineno,yylineno);
  return INCOP;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 333 "Lexical.l"
{
  string oprt=yytext;
  string token="RELOP";
  PrintLogFile(line_count,token,oprt);
  //PrintTokenFile(token,oprt);
  yylval.symbol=new symbolInfo(yytext,"RELOP",yylineno,yylineno);
  return RELOP;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 341 "Lexical.l"
{
  string oprt=yytext;
  string token="ASSIGNOP";
  PrintLogFile(line_count,token,oprt);
  //PrintTokenFile(token,oprt);
  yylval.symbol=new symbolInfo(yytext,"ASSIGNOP",yylineno,yylineno);
  return ASSIGNOP;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 349 "Lexical.l"
{
  string oprt=yytext;
  string token="LOGICOP";
  PrintLogFile(line_count,token,oprt);
  //PrintTokenFile(token,oprt);
  yylval.symbol=new symbolInfo(yytext,"LOGICOP",yylineno,yylineno);
  return LOGICOP;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 357 "Lexical.l"
{
  string oprt=yytext;
  string token="NOT";
  PrintLogFile(line_count,token,oprt);
  //PrintTokenFile(token,oprt);
  yylval.symbol=new symbolInfo(yytext,"NOT",yylineno,yylineno);
  return NOT;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 365 "Lexical.l"
{
  string oprt=yytext;
  string token="LPAREN";
  PrintLogFile(line_count,token,oprt);
  //PrintTokenFile(token,oprt);
  yylval.symbol=new symbolInfo(yytext,"LPAREN",yylineno,yylineno);
  return LPAREN;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 373 "Lexical.l"
{
  string oprt=yytext;
  string token="RPAREN";
  PrintLogFile(line_count,token,oprt);
  //PrintTokenFile(token,oprt);
  yylval.symbol=new symbolInfo(yytext,"RPAREN",yylineno,yylineno);
  return RPAREN;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 381 "Lexical.l"
{
  string oprt=yytext;
  string token="LCURL";
  PrintLogFile(line_count,token,oprt);
  //PrintTokenFile(token,oprt);
  yylval.symbol=new symbolInfo(yytext,"LCURL",yylineno,yylineno);
  return LCURL;
  //st.EnterScope();
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 390 "Lexical.l"
{
  string oprt=yytext;
  string token="RCURL";
  PrintLogFile(line_count,token,oprt);
  yylval.symbol=new symbolInfo(yytext,"RCURL",yylineno,yylineno);
  return RCURL;
  //PrintTokenFile(token,oprt);
  //st.exitScope();
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 400 "Lexical.l"
{
  string oprt=yytext;
  string token="LSQUARE";
  PrintLogFile(line_count,token,oprt);
  yylval.symbol=new symbolInfo(yytext,"LSQUARE",yylineno,yylineno);
  return LSQUARE;
  //PrintTokenFile(token,oprt);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 408 "Lexical.l"
{
  string oprt=yytext;
  string token="RSQUARE";
  PrintLogFile(line_count,token,oprt);
  //PrintTokenFile(token,oprt);
  yylval.symbol=new symbolInfo(yytext,"RSQUARE",yylineno,yylineno);
  return RSQUARE;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 416 "Lexical.l"
{
  string oprt=yytext;
  string token="COMMA";
  PrintLogFile(line_count,token,oprt);
  //PrintTokenFile(token,oprt);
  yylval.symbol=new symbolInfo(yytext,"COMMA",yylineno,yylineno);
  return COMMA;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 425 "Lexical.l"
{
  string oprt=yytext;
  string token="SEMICOLON";
  PrintLogFile(line_count,token,oprt);
  //PrintTokenFile(token,oprt);
  yylval.symbol=new symbolInfo(yytext,"SEMICOLON",yylineno,yylineno);
  return SEMICOLON;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 435 "Lexical.l"
{
  PrintLogFileError(line_count,"TOO_MANY_DECIMAL_POINTS",yytext);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 438 "Lexical.l"
{
  PrintLogFileError(line_count,"ILLFORMED_NUMBER",yytext);
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 441 "Lexical.l"
{
  PrintLogFileError(line_count,"INVALID_ID_SUFFIX_NUM_PREFIX",yytext);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 444 "Lexical.l"
{
  PrintLogFileError(line_count,"MULTICHAR_CONST_CHAR",yytext);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 447 "Lexical.l"
{
  PrintLogFileError(line_count,"EMPTY_CONST_CHAR",yytext);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 450 "Lexical.l"
{
  PrintLogFileError(line_count,"UNFINISHED_CONST_CHAR",yytext);
}
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 453 "Lexical.l"
{
  for(int i=0;i<strlen(yytext);i++){
    if(yytext[i]=='\n') line_count++;
  }
  PrintLogFileError(line_count,"UNFINISHED_COMMENT",yytext);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 460 "Lexical.l"
{
  return 0;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 463 "Lexical.l"
{
  PrintLogFileError(line_count,"UNRECOGNIZED_CHAR",yytext);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 466 "Lexical.l"
ECHO;
	YY_BREAK
#line 1539 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 174 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 174 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 173);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 466 "Lexical.l"



